### ISSUE TITLE
Error: The plugin typedoc-plugin-localization could not be loaded

### ISSUE THREAD

**Issue by dreadnya** [IgniteUI/typedoc-plugin-localization#59]
Any command entered gives this error. I can’t understand what I’m doing wrong.

`Error: The plugin /home/levanov/projects/tssdk/node_modules/typedoc-plugin-localization could not be loaded.
Info: TypeError: Cannot read property 'forEach' of undefined
    at module.exports (/home/levanov/projects/tssdk/node_modules/typedoc-plugin-localization/dist/index.js:20:20)
    at PluginHost.load (/home/levanov/projects/tssdk/node_modules/typedoc/dist/lib/utils/plugins.js:39:21)
    at Application.bootstrap (/home/levanov/projects/tssdk/node_modules/typedoc/dist/lib/application.js:83:22)
    at Object.<anonymous> (/home/levanov/projects/tssdk/node_modules/typedoc/bin/typedoc:25:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
`

TypeDoc 0.20.36
TypeScript 4.0.5

**Comment by Aleksandyr** [comment]
@dreadnya Could you please tell me which version of the plugin you are using and can you please try executing the plugin again, because we have made some changes in the latest 2.2.4v.
